NumPy functions that operates on the ndarray object

ufuncs also take additional arguments, like:

where boolean array or condition defining where the operations should take place.
dtype defining the return type of elements.
out output array where the return value should be copied. 

Converting iterative statements into a vector based operation is called vectorization.
It is faster as modern CPUs are optimized for such operations.

Without ufunc, we can use Python's built-in zip() method:

In [1]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z) 

[5, 7, 9, 11]


NumPy has a ufunc for this, called add(x, y) that will produce the same result.

In [3]:
import numpy as np

x1 = [1, 2, 3, 4]
y1 = [4, 5, 6, 7]
z1 = np.add(x1, y1)

print(z1) 

[ 5  7  9 11]


To create you own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

    function - the name of the function.
    inputs - the number of input arguments (arrays).
    outputs - the number of output arrays.


In [4]:
def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8])) 

[6 8 10 12]


Check the type of a function to check if it is a ufunc or not.

A ufunc should return <class 'numpy.ufunc'>.

In [5]:
print(type(np.add)) 

<class 'numpy.ufunc'>


In [6]:
def testingstuff(a):
    return print(a)

# this throws an error
print(type(np.testingstuff))


AttributeError: module 'numpy' has no attribute 'testingstuff'

In [7]:
print(type(np.concatenate)) 

<class 'function'>


In [8]:
print(type(np.blahblah)) 

AttributeError: module 'numpy' has no attribute 'blahblah'

In [9]:
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc') 

add is ufunc


****Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.****

All of the arithmetic functions take a ***where*** parameter in which we can specify that condition.

In [11]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# this add method is not the one I created above, this is a built in method

newarr = np.add(arr1, arr2)

print(newarr) 

[30 32 34 36 38 40]


In [12]:
newarr2 = np.subtract(arr1, arr2)

print(newarr2) 

[-10 -10 -10 -10 -10 -10]


In [13]:
newarr3 = np.multiply(arr1, arr2)

print(newarr3) 

[200 231 264 299 336 375]


In [14]:
arr3 = np.array([10, 20, 30, 40, 50, 60])
arr4 = np.array([3, 5, 10, 8, 2, 33])

newarr3 = np.divide(arr3, arr4)

print(newarr3)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [17]:
arr5 = np.array([10, 20, 29, 40, 50, 60])
arr6 = np.array([3, 5, 6, 8, 2, 33])

# Raise the valules in arr1 to the power of values in arr2 

newarr4 = np.power(arr5, arr6)

print(newarr4) 

[      1000    3200000  594823321 -520093696       2500          0]


In [18]:
#  Returningn the remainders

newarr5 = np.mod(arr5, arr6)

# np.remainder would give the same results

print(newarr5) 

[ 1  0  5  0  0 27]
