The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr) 

(array([ 3,  2,  3,  5, 25,  1], dtype=int32), array([ 1,  6,  3,  0,  0, 27], dtype=int32))


Both the absolute() and the abs() functions functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [2]:

arr2 = np.array([-1, -2, 1, 2, 3, -4])

newarr2 = np.absolute(arr2)

print(newarr2) 

[1 2 1 2 3 4]


There are primarily five ways of rounding off decimals in NumPy:

    truncation
    fix
    rounding
    floor
    ceil



Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions

In [3]:

arr3 = np.trunc([-3.1666, 3.6667])

print(arr3) 

[-3.  3.]


In [4]:
arr4 = np.fix([-3.1666, 3.6667])

print(arr4) 

[-3.  3.]


The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

In [9]:
arr5 = np.around(3.1666, 2)
arr6 = np.around(6.1666, 3)
arr7 = np.around(4.724, 1)


print(arr5)
print(arr6)
print(arr7)

3.17
6.167
4.7


The floor() function rounds off decimal to nearest lower integer (not 0, for that trunc or fix can be used).

In [10]:
arr8 = np.floor([-3.1666, 3.6667])

print(arr8) 

[-4.  3.]


The ceil() function rounds off decimal to nearest upper integer.

In [11]:
arr9 = np.ceil([-3.1666, 3.6667])

print(arr9) 

[-3.  4.]


# logs

NumPy provides functions to perform log at the base 2, e and 10.

In [15]:
# Find log at base 2 of all elements of following array:

# The arange(1, 10) function returns an array with integers starting from 1 (included) to 10 (not included)

arr10 = np.arange(1, 10)
arr11 = np.arange(2, 10)

print(np.log2(arr10)) 
print(np.log2(arr11))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[1.         1.5849625  2.         2.32192809 2.5849625  2.80735492
 3.         3.169925  ]


Use the log10() function to perform log at the base 10.

In [17]:
arr11 = np.arange(1, 10)
print("arr11 ==>", arr11)
print(np.log10(arr11))

arr11 ==> [1 2 3 4 5 6 7 8 9]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


Use the log() function to perform log at the base e.

In [18]:
arr12 = np.arange(1, 10)

print(np.log(arr12)) 

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [19]:
 from math import log
# NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt
# function math.log() with two input parameters and one output parameter:   
nplog = np.frompyfunc(log, 2, 1)

print(nplog)
print(nplog(100, 15)) 

<ufunc 'log (vectorized)'>
1.7005483074552052


# Summations

Addition is done between two arguments whereas summation happens over n elements.

In [25]:
arr13 = np.array([1, 2, 3])
arr14 = np.array([1, 2, 3])

newarr3 = np.add(arr13, arr14)

# don't forget to use square brackets when using sum
newarr4 = np.sum([arr13, arr14])

print(newarr4)
print(newarr3) 

12
[2 4 6]


Summation over an axis

In [26]:
newarr5 = np.sum([arr13, arr14], axis=1)

print(newarr5)

[6 6]


Cummulative sum

In [27]:
# The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10], an example

# performing partial sum with cumsum() method

arr15 = np.array([1, 2, 3])

newarr6 = np.cumsum(arr15)

print(newarr6) 

[1 3 6]


# Products

In [29]:
# To find the product of the elements in an array, use the prod() function.
arr16 = np.array([1, 2, 3, 4])

x = np.prod(arr16)

print(x, " ==> Returns: 24 because 1*2*3*4 = 24") 

24  ==> Returns: 24 because 1*2*3*4 = 24


In [31]:
arr16 = np.array([1, 2, 3, 4])
arr17 = np.array([5, 6, 7, 8])

x2 = np.prod([arr16, arr17])

print(x2, " ==> 40320 because 1*2*3*4*5*6*7*8 = 40320") 

40320  ==> 40320 because 1*2*3*4*5*6*7*8 = 40320


Product over an axis

In [33]:
# If you specify axis=1, NumPy will return the product of each array.
# Perform summation in the following array over 1st axis

newarr7 = np.prod([arr16, arr17], axis=1)

print(newarr7) 

[  24 1680]


Cummulative Product

In [34]:
# Cummulative product means taking the product partially, using both partial and product.

# E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

arr18 = np.array([5, 6, 7, 8])

newarr8 = np.cumprod(arr18)

print(newarr8) 

[   5   30  210 1680]


# Differences


A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.


In [36]:
arr19 = np.array([10, 15, 25, 5])

newarr9 = np.diff(arr19)

print(newarr9, " ==> Returns: [5 10 -20] because 15-10=5, 25-15=10, and 5-25=-20") 

[  5  10 -20]  ==> Returns: [5 10 -20] because 15-10=5, 25-15=10, and 5-25=-20


We can perform this operation repeatedly by giving parameter n.
E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0] 

In [38]:
arr20 = np.array([10, 15, 25, 5])

newarr10 = np.diff(arr20, n=2)

print(newarr10, " ==> Returns: [5 -30] because: 15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10=-30") 

[  5 -30]  ==> Returns: [5 -30] because: 15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10=-30


# Finding LCM (Lowest Common Multiple)

In [39]:
num1 = 4
num2 = 6

x3 = np.lcm(num1, num2)

print(x3)

12


To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.
The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.

In [42]:
arr21 = np.array([3, 6, 9])

x4 = np.lcm.reduce(arr21)

print(x4, "<== x4") 

arr22 = np.arange(1, 11)
print(arr22, "<== arr22")
x5 = np.lcm.reduce(arr22)

print(x5, "<== x5") 

18 <== x4
[ 1  2  3  4  5  6  7  8  9 10] <== arr22
2520 <== x5


# Finding GCD (Greatest Common Denominator)

Also known as HCF(highest commong factor)

In [44]:
num3 = 6
num4 = 9

x6 = np.gcd(num3, num4)

print(x6) 

num5 = 7
num6 = 6

x7 = np.gcd(num5, num6)

print(x7)

3
1


The reduce() method will use the ufunc, in this case the gcd() function, on each element, and reduce the array by one dimension.

In [45]:
arr23 = np.array([20, 8, 32, 36, 16])

x8 = np.gcd.reduce(arr23)

print(x8) 

4


# Trigonometric Functions

NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [46]:
# sin of PI/2
x9 = np.sin(np.pi/2)

print(x9) 

1.0


In [47]:
arr22 = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x10 = np.sin(arr22)

print(x10) 

[1.         0.8660254  0.70710678 0.58778525]


Converting degrees into radians

In [48]:
arr23 = np.array([90, 180, 270, 360])

x11 = np.deg2rad(arr23)

print(x11) 

[1.57079633 3.14159265 4.71238898 6.28318531]


Converting radians into degrees

In [49]:
arr24 = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x12 = np.rad2deg(arr24)

print(x12) 

[ 90. 180. 270. 360.]


Finding angles

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [50]:
x13 = np.arcsin(1.0)

print(x13) 

1.5707963267948966


In [51]:
arr25 = np.array([1, -1, 0.1])

x14 = np.arcsin(arr25)

print(x14) 

[ 1.57079633 -1.57079633  0.10016742]


Hypotenues

In [52]:
base = 3
perp = 4

x15 = np.hypot(base, perp)

print(x15) 

5.0


# Hyperbolic Functions

NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values..

In [53]:
x16 = np.sinh(np.pi/2)

print(x16) 

2.3012989023072947


In [54]:
arr26 = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x17 = np.cosh(arr26)

print(x17) 

[2.50917848 1.60028686 1.32460909 1.20397209]


Finding Angles

Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.

In [55]:
x18 = np.arcsinh(1.0)

print(x18) 

0.881373587019543


In [56]:
arr27 = np.array([0.1, 0.2, 0.5])

x18 = np.arctanh(arr27)

print(x18) 

[0.10033535 0.20273255 0.54930614]


# NumPy Set Operations

A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

In [57]:
arr28 = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x19 = np.unique(arr28)

print(x19) 

[1 2 3 4 5 6 7]


To find the unique values of two arrays, use the union1d() method

In [58]:
arr29 = np.array([1, 2, 3, 4])
arr30 = np.array([3, 4, 5, 6])

newarr10 = np.union1d(arr29, arr30)

print(newarr10) 

[1 2 3 4 5 6]


To find only the values that are present in both arrays, use the intersect1d() method.

In [59]:
arr31 = np.array([1, 2, 3, 4])
arr32 = np.array([3, 4, 5, 6])

newarr11 = np.intersect1d(arr31, arr32, assume_unique=True)

print(newarr11) 

[3 4]


Note: the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

In [62]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr12 = np.setdiff1d(set1, set2, assume_unique=True)


print(newarr12, "<== these are the values not present in the second array") 

[1 2] <== these are the values not present in the second array


***Note***: the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

Finding Symmetric Difference

To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [63]:
newarr13 = np.setxor1d(set1, set2, assume_unique=True)

print(newarr13) 

[1 2 5 6]


***Note***: the setxor1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.